### ISSUE TITLE
Large images stretched out of border in PDF

### ISSUE THREAD

**Issue by wayneko** [oxygenxml/ditaMark#2]
Hi, thanks for your great work! But it seems that large images referenced in Markdown files will be stretched out of border in rendered PDF. How to solve this issue please?

![sample](https://user-images.githubusercontent.com/15225867/37075593-88ce3e7e-220d-11e8-85a6-77a646b36a74.png)

**Comment by raducoravu** [comment]
There does not seem to be a standard way to specify an image's width in Markdown so maybe you could scale down the image before referring to it.
Or after you convert the Markdown to DITA using the quick fix, you could try to add a @scale or a @width attribute on the DITA image element.

**Comment by georgebina** [comment]
Alternatively, the quick fix that converts the Markdown fragment to a DITA image can also add the scale-fit="yes" attribute.  For example after this line
https://github.com/oxygenxml/ditaMark/blob/553c06ce0be5e0ad8c47f712373ed83826d33885/frameworks/ditaMark/rules/md2dita.sch#L53
add
```xml
<xsl:attribute name="scale-fit" select="'yes'"/>
```
Regards,
George
